#!/bin/bash

# Copyright (c) 2026 Battelle Energy Alliance, LLC.  All rights reserved.

FILESCAN_HTTP_SERVER_ASSETS_DIR=${FILESCAN_HTTP_SERVER_ASSETS_DIR:-/assets}
FILESCAN_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER=${FILESCAN_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER:-/assets}
[[ "${MALCOLM_PROFILE:-malcolm}" == "malcolm" ]] && \
  FILESCAN_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER=${FILESCAN_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER:-/extracted-files/assets} || \
  FILESCAN_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER=${FILESCAN_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER:-/assets}
export FILESCAN_HTTP_SERVER_ASSETS_DIR
export FILESCAN_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER
export FILESCAN_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER

exec "$@"
