# Copyright (c) 2026 Battelle Energy Alliance, LLC.  All rights reserved.

name: "${PCAP_NODE_NAME:malcolm}"

logging.metrics.enabled: false

#================================ Inputs =======================================

filebeat.inputs:

#-------------------------- "Real" Zeek logs -----------------------------------
- type: filestream
  id: zeek-upload
  take_over.enabled: true
  paths:
    - ${FILEBEAT_ZEEK_LOG_PATH:/zeek/current}/*.log
  prospector:
    scanner:
      exclude_files: ['json_streaming_.+\.log$']
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  fields_under_root: true
  tags: ["_filebeat_zeek_malcolm_upload"]
  exclude_lines: ['^\s*#']
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE:120s}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: ${FILEBEAT_CLOSE_EOF:true}
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

- type: filestream
  id: zeek-live
  take_over.enabled: true
  paths:
    - ${FILEBEAT_ZEEK_LOG_LIVE_PATH:/zeek/live}/spool/logger-*/*.log
  prospector:
    scanner:
      exclude_files: ['json_streaming_.+\.log$']
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  fields_under_root: true
  tags: ["_filebeat_zeek_malcolm_live"]
  exclude_lines: ['^\s*#']
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: false
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#-------------------------- File scanning/pipeline result log ------------------
# (c.f. comments regarding settings from previous section)
- type: filestream
  id: filescan
  take_over.enabled: true
  paths:
    - ${FILEBEAT_FILESCAN_LOG_PATH:/filescan}/*.log
  prospector:
    scanner:
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  fields_under_root: true
  parsers:
    - ndjson:
        expand_keys: true
        add_error_key: false
        ignore_decoding_error: true
        target: ""
  processors:
    - rename:
        fields:
          - from: "source"
            to: "service.type"
  tags: ["_filebeat_filescan"]
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
      renamed: false
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: false
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#-------------------------- Suricata EVE JSON logs -----------------------------
- type: filestream
  id: eve-upload
  take_over.enabled: true
  paths:
    - ${FILEBEAT_SURICATA_LOG_PATH:/suricata}/suricata-*/eve*.json
  prospector:
    scanner:
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  fields_under_root: true
  tags: ["_filebeat_suricata_malcolm_upload"]
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      # We're now submitting uploaded PCAP to Suricata over a socket,
      #   but Suricata doesn't let us know when processing is complete.
      #   Reaching EOF doesn't necessarily mean the file is done
      #   being written to. We need to treat the results more like "live"
      #   even though the traffic itself isn't.
      on_eof: false
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

- type: filestream
  id: eve-live
  take_over.enabled: true
  paths:
    - ${FILEBEAT_SURICATA_LOG_PATH:/suricata}/live/eve*.json
  prospector:
    scanner:
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  fields_under_root: true
  tags: ["_filebeat_suricata_malcolm_live"]
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: false
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#-------------------------- Uploaded Windows EVTX Logs (as JSON) ---------------
#                           (see evtx_to_jsonl.sh)
- type: filestream
  id: evtx
  take_over.enabled: true
  paths:
    - ${FILEBEAT_ZEEK_LOG_PATH:/zeek/current}/*.evtx.json
  prospector:
    scanner:
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  parsers:
    - ndjson:
        expand_keys: true
        add_error_key: false
        ignore_decoding_error: true
        target: "json"
  tags: ["_evtx_to_json"]
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE:120s}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: ${FILEBEAT_CLOSE_EOF:true}
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#-------------------------- network interface stats (as JSON) ---------------
#                           (see netdev-json.sh)
- type: filestream
  id: netdev-stats
  take_over.enabled: true
  paths:
    - ${FILEBEAT_ZEEK_LOG_LIVE_PATH:/zeek/live}/netdev-stats*.json
  prospector:
    scanner:
      symlinks: true
      check_interval: ${FILEBEAT_SCAN_FREQUENCY:10s}
  parsers:
    - ndjson:
        expand_keys: false
        add_error_key: false
        ignore_decoding_error: true
        target: miscbeat.network
  fields:
    miscbeat.module: network
  processors:
    - rename:
        fields:
          - from: "fields.miscbeat.module"
            to: "miscbeat.module"
          - from: "json"
            to: "miscbeat.network"
  tags: ["_malcolm_beats", "_malcolm_miscbeat"]
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close:
    on_state_change:
      inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
      renamed: ${FILEBEAT_CLOSE_RENAMED:true}
      removed: ${FILEBEAT_CLOSE_REMOVED:true}
    reader:
      on_eof: true
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#================================ Outputs ======================================

#-------------------------- Logstash Output ------------------------------------
output.logstash:
  hosts: ["${LOGSTASH_HOST:logstash:5044}"]
  ssl.enabled: ${BEATS_SSL:false}
  ssl.certificate_authorities: ["/certs/ca.crt"]
  ssl.certificate: "/certs/client.crt"
  ssl.key: "/certs/client.key"
  ssl.supported_protocols: "TLSv1.2"
  ssl.verification_mode: "none"
