# Copyright (c) 2025 Battelle Energy Alliance, LLC.  All rights reserved.

name: "${PCAP_NODE_NAME:malcolm}"

logging.metrics.enabled: false

#================================ Inputs =======================================

#-------------------------- JSON-formatted files.log ---------------------------
filebeat.inputs:
- type: log
  paths:
    - ${FILEBEAT_ZEEK_LOG_PATH:/zeek/current}/json_streaming_files*.log
  symlinks: true
  fields_under_root: true
  compression_level: 0
  scan_frequency: ${FILEBEAT_SCAN_FREQUENCY:10s}
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close_inactive: ${FILEBEAT_CLOSE_INACTIVE:120s}
  close_renamed: ${FILEBEAT_CLOSE_RENAMED:true}
  close_removed: ${FILEBEAT_CLOSE_REMOVED:true}
  close_eof: ${FILEBEAT_CLOSE_EOF:true}
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

- type: log
  paths:
    - ${FILEBEAT_ZEEK_LOG_LIVE_PATH:/zeek/live}/spool/logger-*/json_streaming_files*.log
  symlinks: true
  fields_under_root: true
  compression_level: 0
  scan_frequency: ${FILEBEAT_SCAN_FREQUENCY:10s}
  clean_inactive: ${FILEBEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${FILEBEAT_IGNORE_OLDER:120m}
  close_inactive: ${FILEBEAT_CLOSE_INACTIVE_LIVE:90m}
  close_renamed: ${FILEBEAT_CLOSE_RENAMED:true}
  close_removed: ${FILEBEAT_CLOSE_REMOVED:true}
  close_eof: false
  clean_removed: ${FILEBEAT_CLEAN_REMOVED:true}

#=============================== Processors ===================================

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: true
      target: "file"
  - drop_event:
      when:
        not:
          has_fields: ["file.extracted"]
  - copy_fields:
      fields:
        - from: "file"
          to: "_keep_file"
      ignore_missing: true
  - drop_fields:
      fields:
        - "/^[A-Za-z0-9].*/"
      ignore_missing: true
  - rename:
      fields:
        - from: "_keep_file"
          to: "file"
      ignore_missing: true
  - script:
      lang: javascript
      params:
        file_path: ${ZEEK_EXTRACTOR_PATH:/zeek/extract_files}
      source: >
        var params = {file_path: "/zeek/extract_files"};
        function register(scriptParams) {
            params = scriptParams;
        }
        function process(event) {
          var prefix = params.file_path;
          var field = event.Get("file.extracted");
          if (!prefix || !field) return;
          if (prefix.charAt(prefix.length - 1) === "/") prefix = prefix.slice(0, -1);
          event.Put("file.extracted", prefix + "/" + field);
        }

#================================ Outputs ======================================

#-------------------------- Redis Output (for filescan) ------------------------
output.redis:
  hosts: ["${REDIS_HOST:redis-cache}:${REDIS_PORT:6379}"]
  password: "${REDIS_PASSWORD}"
  db: ${REDIS_ZEEK_FILES_DATABASE:1}
  key: "zeek_notify"
  datatype: "list"
