ScanCapa:
  - positive:
      flavors:
        # todo: is this list exhaustive? are there more types that should be included
        - 'application/bat'
        - 'application/ecmascript'
        - 'application/javascript'
        - 'application/PowerShell'
        - 'application/vnd.microsoft.portable-executable'
        - 'application/x-bat'
        - 'application/x-coredump'
        - 'application/x-dosexec'
        - 'application/x-elf'
        - 'application/x-executable'
        - 'application/x-msdos-program'
        - 'application/x-msdownload'
        - 'application/x-object'
        - 'application/x-pe-app-32bit-i386'
        - 'application/x-sh'
        - 'application/x-sharedlib'
        - 'text/jscript'
        - 'text/vbscript'
        - 'text/x-python'
        - 'text/x-shellscript'
    priority: 5
    scanner_timeout: 600
