ScanYara:
  - positive:
      flavors:
        - "*"
    priority: 5
    options:
      location: "/yara-rules"
      compiled:
        enabled: True
        filename: "rules.compiled"
      category_key: "scope"
      categories:
        collection:
          show_meta: False
        detection:
          show_meta: True
        information:
          show_meta: False
      meta_fields:
        - "author"
        - "description"
        - "hash"
        - "intel"
      show_all_meta: False
      store_offset: True
      offset_meta_key: "StrelkaHexDump"
      offset_padding: 32
    scanner_timeout: 300
