ScanX509:
  - positive:
      flavors:
        - 'x509_der_file'
    priority: 5
    options:
      type: 'der'
  - positive:
      flavors:
        - 'x509_pem_file'
    priority: 5
    options:
      type: 'pem'
