#!/bin/bash

# Copyright (c) 2025 Battelle Energy Alliance, LLC.  All rights reserved.

EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR=${EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR:-/assets}
EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER=${EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER:-/assets}
[[ "${MALCOLM_PROFILE:-malcolm}" == "malcolm" ]] && \
  EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER=${EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER:-/extracted-files/assets} || \
  EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER=${EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER:-/assets}
export EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR
export EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_REQ_REPLACER
export EXTRACTED_FILE_HTTP_SERVER_ASSETS_DIR_RESP_REPLACER

exec "$@"
