# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload plugin is not installed!'
end

# hack: https://github.com/hashicorp/vagrant/issues/8878#issuecomment-345112810
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "../shared", "/vagrant", disabled: false

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
    vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--vram", 64]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  config.vm.provision "shell", inline: <<-STEP1
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y gnupg2 curl ca-certificates libcap2-bin python3-minimal python-is-python3
    curl -sSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" >> /etc/apt/sources.list
    apt-get update
    apt-get install -y filebeat=7.6.2
  STEP1

  config.vm.provision "file", source: "./filebeat.yml", destination: "/tmp/filebeat.yml"
  config.vm.provision "file", source: "../beat_run.py", destination: "/tmp/beat_run.py"
  config.vm.provision "file", source: "../beat_config.py", destination: "/tmp/beat_config.py"
  config.vm.provision "file", source: "../beat_common.py", destination: "/tmp/beat_common.py"

  config.vm.provision "shell", inline: <<-STEP2
    export DEBIAN_FRONTEND=noninteractive
    filebeat modules enable system
    mkdir -p /opt/filebeat
    mv /tmp/filebeat.yml /opt/filebeat
    mv /tmp/beat*.py /opt/filebeat
    chown -R root:root /opt/filebeat
    chmod 700 /opt/filebeat
    chmod 600 /opt/filebeat/*
    chmod 700 /opt/filebeat/*.py
  STEP2

  config.vm.provision :reload

end
