# Copyright (c) 2026 Battelle Energy Alliance, LLC.  All rights reserved.

# final adjustments before forwarding

filter {

  fingerprint {
    id => "fingerprint_filescan_hash"
    source => [ "[source][ip]",
                "[destination][ip]",
                "[firstPacket]",
                "[lastPacket]",
                "[event][module]",
                "[host][name]",
                "[file][hash][sha256]",
                "[rule][ruleset]",
                "[filescan][tree][root]",
                "[filescan][tree][node]",
                "[filescan][tree][parent]",
                "[filescan][tree][depth]",
                "[rule][name]" ]
    concatenate_sources => true
    ecs_compatibility => "v8"
    method => "MURMUR3_128"
    base64encode => true
  }

  ruby {
      id => "ruby_filescan_move_results_up_and_remove_parent_fields"
      code => "
        Hash(event.get('[results]') || {}).each do |k, v|
          event.set('[' + k + ']', v)
        end

        # for Strelka results for archived/nested files, remove ome of the zeek.files fields (which belong to the 'parent')
        [
            '[zeek][files][analyzers]',
            '[zeek][files][depth]',
            '[zeek][files][duration]',
            '[zeek][files][extracted]',
            '[zeek][files][extracted_cutoff]',
            '[zeek][files][extracted_size]',
            '[zeek][files][ftime]',
            '[zeek][files][local_orig]',
            '[zeek][files][md5]',
            '[zeek][files][mime_type]',
            '[zeek][files][missing_bytes]',
            '[zeek][files][overflow_bytes]',
            '[zeek][files][seen_bytes]',
            '[zeek][files][sha1]',
            '[zeek][files][sha256]',
            '[zeek][files][ssdeep]',
            '[zeek][files][timedout]',
            '[zeek][files][tlsh]',
            '[zeek][files][total_bytes]'
        ].each do |field|
          event.remove(field)
        end if event.get('[filescan][tree][depth]').to_i.positive?
      "
  }

  mutate {
    id => "mutate_filescan_remove_field_useless"
    remove_field => [
      "[file][sha256]",
      "[id]",
      "[results]",
      "[metadata][record]",
      "[strelka][result][request][attributes][metadata][record]",
      "[strelka][result][file][metadata][record]",
      "[entity][raw]"
    ]
  }

}
