version: 2025.12.16.01
logging_cfg: '/etc/strelka/logging.yaml'
limits:
  max_files: 10000
  time_to_live: 3600
  max_depth: 15
  distribution: 1800
  scanner: 180
coordinator:
  addr: 'strelka-coordinator:6379'
  db: 0
  password: null
tasting:
  mime_db: null
  yara_rules: '/etc/strelka/taste/'
caching:
  scanner: true
telemetry:
  traces:
    sampling: 0.0
scanners:
