error_page 401 /401.html;
error_page 404 /404.html;
error_page 502 /502.html;

location = /401.html {
  internal;
  root /usr/share/nginx/html;
}

location = /404.html {
  internal;
  root /usr/share/nginx/html;
}

location = /502.html {
  internal;
  root /usr/share/nginx/html;
}
