---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: malcolm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      name: valkey
  selector:
    app: valkey

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  namespace: malcolm
  labels:
    app: valkey
    role: database
spec:
  selector:
    matchLabels:
      app: valkey
  replicas: 1
  template:
    metadata:
      labels:
        app: valkey
        role: database
    spec:
      containers:
      - name: valkey-container
        image: ghcr.io/idaholab/malcolm/valkey:26.04.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        command: ["/sbin/tini"]
        args: ["--",
               "/usr/local/bin/docker-uid-gid-setup.sh",
               "/usr/local/bin/service_check_passthrough.sh",
               "-s",
               "valkey",
               "sh",
               "-c",
               "valkey-server --dir /data --appendonly yes --appendfsync everysec --no-appendfsync-on-rewrite yes --auto-aof-rewrite-percentage 100 --auto-aof-rewrite-min-size $(VALKEY_AUTO_AOF_REWRITE_MIN_SIZE) --save '' --maxmemory $(VALKEY_MAXMEMORY) --maxmemory-policy $(VALKEY_MAXMEMORY_POLICY) --requirepass $(VALKEY_PASSWORD)"]
        ports:
          - name: valkey
            protocol: TCP
            containerPort: 6379
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - secretRef:
              name: valkey-env
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 45
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: valkey-var-local-catrust-volume
          - mountPath: /data
            name: valkey-volume
            subPath: valkey
      initContainers:
      - name: valkey-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:26.04.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:valkey"
        volumeMounts:
          - name: valkey-volume
            mountPath: "/data/config"
      volumes:
        - name: valkey-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: valkey-volume
          persistentVolumeClaim:
            claimName: config-claim