# Copyright (c) 2025 Battelle Energy Alliance, LLC.  All rights reserved.

# hack: https://github.com/hashicorp/vagrant/issues/8878#issuecomment-345112810
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|

  config.vm.define "vagrant-malcolm-build"
  config.vm.box = "bento/debian-13"

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "../..", "/malcolm-build",
    disabled: false,
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: [".git/",
                     "netbox/media/",
                     "malcolm-iso/malcolm-*.*",
                     "hedgehog-raspi/raspi_4_*.*"]
  config.vm.synced_folder '.', '/vagrant', disabled: true

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = "8192"
    lv.cpus = 4
  end

  config.vm.provider "vmware_desktop" do |vd|
    vd.memory = "8192"
    vd.cpus = 4
  end

  config.vm.provider "vmware_fusion" do |vf|
    vf.memory = "8192"
    vf.cpus = 4
  end

  config.vm.provision "shell", inline: <<-STEP1
    dpkg-reconfigure debconf -f noninteractive -p critical
    export DEBIAN_FRONTEND=noninteractive
    sed -i "s/main/main contrib non-free non-free-firmware/g" /etc/apt/sources.list
    apt-get -qqy update
    apt-get -y install \
      apt-transport-https \
      bc \
      build-essential \
      ca-certificates \
      curl \
      debootstrap \
      dkms \
      gcc \
      genisoimage \
      git \
      gnupg2 \
      imagemagick \
      jq \
      linux-headers-amd64 \
      live-build \
      rsync \
      squashfs-tools \
      virt-what \
      xmlstarlet \
      xorriso
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get -qqy update
    apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    ln -s -r /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
    usermod -a -G docker vagrant
  STEP1
end