filter {

  ################################################################################################
  # Do enrichment based on OTKB lookups

  if ([zeek] and ("ot" in [event][category])) or [wireshark] {
    ruby {
      id => "ruby_otkb_enrich"
      tag_on_exception => "_rubyexception_otkb_enrich"
      path => "/usr/share/logstash/malcolm-ruby/otkb_enrich.rb"
      script_params => {
          "enabled_env" => "OTKB_ENRICHMENT"
          "otkb_url_env" => "OTKB_URL"
          "otkb_json_fixture_file_env" => "OTKB_JSON_FIXTURE_FILE"
          "otkb_token_env" => "OTKB_TOKEN"
          "cache_ttl_env" => "OTKB_ENRICHMENT_TTL"
          "ssl_verify_env" => "OTKB_SSL_VERIFY"
          "verbose_env" => "OTKB_ENRICHMENT_VERBOSE"
          "debug_env" => "OTKB_ENRICHMENT_DEBUG"
          "debug_timings_env" => "OTKB_ENRICHMENT_DEBUG_TIMINGS"
      }
    }

    if ![event][action] and [otkb][function][name] {
      mutate {
        id => "mutate_merge_otkb_function_name_event_action"
        merge => {
          "[event][action]" => "[otkb][function][name]"
        }
      }
    }
  }

  if [otkb][procedures] and
     ([threat][framework] == "MITRE ATT&CK for ICS") {

    if [threat][technique][id] and ![threat][technique][name] {
      translate {
        id => "translate_otkb_mitre_attack_ics_technique_name"
        iterate_on => "[threat][technique][id]"
        source => "[threat][technique][id]"
        target => "[threat][technique][name]"
        dictionary_path => "/etc/mitre_attack_technique_ics_names.yaml"
      }
    }

    if [threat][tactic][id] and ![threat][tactic][name] {
      translate {
        id => "translate_otkb_mitre_attack_ics_tactic_name"
        iterate_on => "[threat][tactic][id]"
        source => "[threat][tactic][id]"
        target => "[threat][tactic][name]"
        dictionary_path => "/etc/mitre_attack_tactic_ics_names.yaml"
      }
    }

    ruby {
      id => "ruby_flatten_otkb_threat_tactic_names"
      code => "
        names = Array(event.get('[threat][tactic][name]')).flatten.compact.uniq
        if names.empty?
          event.remove('[threat][tactic][name]')
        else
          event.set('[threat][tactic][name]', names)
        end
      "
    }
  }

}
