name: hedgehog-raspi-build-docker-wrap-push-ghcr

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'malcolm-iso/**'
      - 'hedgehog-raspi/**'
      - 'shared/bin/*'
      - '.trigger_iso_workflow_build'
      - '.github/workflows/raspi-build-push.yml'
      - '.github/workflows/hedgehog-raspi-build-docker-wrap-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rpi_model: 4
            rpi_os: trixie
          - rpi_model: 4
            rpi_os: forky
          - rpi_model: 5
            rpi_os: forky

    uses: ./.github/workflows/raspi-build-push.yml

    permissions:
      packages: write
      contents: read
      security-events: write

    with:
      profile: hedgehog
      rpi_model: ${{ matrix.rpi_model }}
      rpi_os: ${{ matrix.rpi_os }}
